### PR TITLE
Loader on long time requests

### PR DESCRIPTION
**Pull request by FacundoBocalandro**
## Description

Added loading icon inside buttons that take a long time to respond and disabled them, that way the user doesn't get confused after pressing them
## ClubHouse Link

https://app.clubhouse.io/bibliotecame/story/350/deshabilitar-botones-durante-request-que-envie-mail
## Checklist
- [X] I've manually tested the feature and it works as expected
- [X] I've successfully integrated the feature with the API
- [X] This pull request has 'sprint_x' as the base branch
- [X] This pull request has a descriptive title and description
- [X] I have merged the current sprint into my branch before pushing
- [X] I've added the QA Leader as a reviewer

### CODE REVIEW

**Review by kuhamaven — APPROVED** [review]
LGTM!

**Review by LucasManza — CHANGES_REQUESTED** [review]
Resultado final:
image

Cuando procesa debe contemplar: 
- Loading sin texto
- Deshabilitado
- Mantener tamaño original del button

**Comment by FacundoBocalandro** [comment]
Listo @LucasManza

**Review by LucasManza — CHANGES_REQUESTED** [review]
Falta disabled y verificar height del button que se mantenga. 
Screenshot from 2020-11-14 19-07-44

**Comment by FacundoBocalandro** [comment]
Listo @LucasManza

**Review by LucasManza — APPROVED** [review]

**Pull request merged**
