### PR TITLE
US-039 User view incorporation request

### PR DESCRIPTION
**Pull request by FacundoBocalandro**
## Description

User can access incorporation request information by clicking on eye icon at incorporation request table.
## ClubHouse Link

https://app.clubhouse.io/bibliotecame/story/264/visualizar-solicitud-de-incorporaci%C3%B3n-alumno
## Checklist
- [X] I've manually tested the feature and it works as expected
- [X] I've successfully integrated the feature with the API
- [X] This pull request has 'sprint_x' as the base branch
- [X] This pull request has a descriptive title and description
- [X] I have merged the current sprint into my branch before pushing
- [X] I've added the QA Leader as a reviewer

### CODE REVIEW

**Comment by rocioferreiro** [comment]
Centrar card.

Screen Shot 2020-11-07 at 13 47 03

**Comment by FacundoBocalandro** [comment]
Ya está solucionado (el centrado vertical) @rocioferreiro.

**Review by LucasManza — CHANGES_REQUESTED** [review]
Al crear una solicitud y luego clickear CANCELAR, muestra la tabla pero no ejecuta ninguna query y no se actualizar:
image
image

Una vez creada la solicitud no me permite volver a ver:
image

Usuarios de prueba:
* francisca.canton@ing.austral.edu.ar --> franchu123
* esther.reyes@ing.austral.edu.ar --> 123qweasd

**Comment by FacundoBocalandro** [comment]
@LucasManza Estás en la branch US-039 del back?

**Comment by LucasManza** [comment]
> Al crear una solicitud y luego clickear CANCELAR, muestra la tabla pero no ejecuta ninguna query y no se actualizar:
> image
> image
> 
> Una vez creada la solicitud no me permite volver a ver:
> image
> 
> Usuarios de prueba:
> 
> * [francisca.canton@ing.austral.edu.ar](mailto:francisca.canton@ing.austral.edu.ar) --> franchu123
> * [esther.reyes@ing.austral.edu.ar](mailto:esther.reyes@ing.austral.edu.ar) --> 123qweasd

**Comment by LucasManza** [comment]
> Ya está solucionado (el centrado vertical) @rocioferreiro.

> @LucasManza Estás en la branch US-039 del back?

Resuelto, paso algo extraño al momento de branchear. Solucionar conflicts para mergear.

**Review by LucasManza — APPROVED** [review]

**Pull request merged**
